name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: "To know whether it's a mod compatibility issue, please remove all other mods and keep only PortalGun and Immersive Portals and Fabric API, backup your world, and then test again whether the issue occurs. Thanks for cooperation."
  - type: dropdown
    id: only_immptl_and_portalgun
    attributes:
      label: According to your testing, does the issue occur with ONLY Portal Gun mod and Immersive Portals mod and Farbic API?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Please tell how to reproduce the issue.
      value: "Describe the issue."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Post the log here
      description: The log is `latest.log` in `logs` folder in the game directory. The log provides useful information (including the mod list) for debugging the issue.
      render: shell
